title: Devloper Chiha
subtitle: 개발자 공부 공간
description: >- # this means to ignore newlines until "baseurl:"
  A Jekyll Theme Built For Developers
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://chihapark.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

author_logo: profile.png
disqus_shortname: chiha park  #for comments using disqus
author: Developer
author_bio: Hello, my name is Chiha Park. I am an Software Developer and Cloud/DB Engineer 
author_email: "chiha3556@gmail.com"
author_location: Seoul
author_website_url: "https://chihapark.github.io"

# social links
twitter_username: yourusername
github_username:  yourusername
facebook_username: yourusername
linkedin_username: yourusername
behance_username: yourusername
instagram_username: yourusername
medium_username: yourusername 
telegram_username: yourusername
dribbble_username: yourusername 
flickr_username: yourusername

# dont touch this unless required
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-analytics

jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-46783401-10      # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking
